name: ztdl 
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=3.5
- pip==9.0.1
- numpy==1.12.0 #linear algebra
- jupyter==1.0 # notebook library
- matplotlib==2.0.0 #plotting
- scikit-learn==0.18.1 #machine learning
- scipy==0.19.0 #organisational algorithms
- pandas==0.19.2 #excel tabular
- pillow==4.0.0 #image library
- seaborn==0.7.1 #
- h5py==2.7.0 #compression library
- pip:
  - tensorflow==1.1.0 
  - keras==2.0.4
